services:
  blog.api:
    image: ${DOCKER_REGISTRY-}blogapi
    build:
      context: .
      dockerfile: Blog.Api/Dockerfile
  blog.db:
    container_name: blog.db
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: blog
    ports:
        - 5432:5432
    volumes: 
        - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
