
services:
  blog.api:
    image: ${DOCKER_REGISTRY-}blogapi
    container_name: blog.api
    build:
      context: .
      dockerfile: Blog.Api/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
  blog.db:
    image: postgres:latest
    container_name: blog.db
    environment:
        - POSTGRES_DB=blog
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
    ports:
        - 5432:5432
    
    volumes: 
        - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
