version: "3.9"
networks:
  blog-api-dev:
    driver: bridge
services:
  app:
    container_name: blog-api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - 8081:8081 
    networks:
        - blog-api-dev
    depends_on:
        - postgress_db
  postgress_db:
    container_name: postgress
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: blog
    ports:
        - 5432:5432
    networks:
        - blog-api-dev
    volumes: 
        - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: